recipes = recipemap('inscryber')
recipes.recipeBuilder()
  .notConsumable(item('appliedenergistics2:material:14'))
  .inputs(metaitem('plateDiamond') * 64)
  .outputs(item('appliedenergistics2:material:17') * 64)
  .duration(1000)
  .EUt(1920)
  .buildAndRegister()
recipes.recipeBuilder()
  .notConsumable(item('appliedenergistics2:material:13'))
  .inputs(metaitem('plateCertusQuartz') * 64)
  .outputs(item('appliedenergistics2:material:16') * 64)
  .duration(1000)
  .EUt(1920)
  .buildAndRegister()
recipes.recipeBuilder()
  .notConsumable(item('appliedenergistics2:material:15'))
  .inputs(metaitem('plateGold') * 64)
  .outputs(item('appliedenergistics2:material:18') * 64)
  .duration(1000)
  .EUt(1920)
  .buildAndRegister()
recipes.recipeBuilder()
  .notConsumable(item('appliedenergistics2:material:19'))
  .inputs(metaitem('plateSilicon') * 64)
  .outputs(item('appliedenergistics2:material:20') * 64)
  .duration(1000)
  .EUt(1920)
  .buildAndRegister()
recipes.recipeBuilder()
  .inputs(ore('circuitLv') * 64)
  .inputs(item('appliedenergistics2:material:20') * 64)
  .inputs(item('appliedenergistics2:material:16') * 64)
  .outputs(item('appliedenergistics2:material:23') * 64)
  .duration(2000)
  .EUt(1920)
  .buildAndRegister()
recipes.recipeBuilder()
  .inputs(ore('circuitLv') * 64)
  .inputs(item('appliedenergistics2:material:20') * 64)
  .inputs(item('appliedenergistics2:material:17') * 64)
  .outputs(item('appliedenergistics2:material:24') * 64)
  .duration(2000)
  .EUt(1920)
  .buildAndRegister()
recipes.recipeBuilder()
  .inputs(ore('circuitLv') * 64)
  .inputs(item('appliedenergistics2:material:20') * 64)
  .inputs(item('appliedenergistics2:material:18') * 64)
  .outputs(item('appliedenergistics2:material:22') * 64)
  .duration(2000)
  .EUt(1920)
  .buildAndRegister()

  crafting.shapedBuilder()
    .name('gregtech:inscriber')
    .output(item('gregtech:machine:32104'))
    .matrix('ACA', 'IMI', 'ACA')
    .key('C', ore('circuitLuv'))
    .key('M', item('gregtech:machine:430'))
    .key('I', item('ae2stuff:inscriber'))
    .key('A', item('minecraft:anvil'))
    .register()
