content.createItem('zpm_power').register()
content.createItem('uv_power').register()
content.createItem('uhv_power').register()
content.createItem('uev_power').register()
content.createItem('uiv_power').register()
content.createItem('uxv_power').register()
content.createItem('opv_power').register()
